
all:
	gcc test_rahmenprogramm.c ../rahmenprogramm.c ../sqrt2.c ../libs/big_num/big_num.c ../libs/decimal_place_converter/decimal_place_converter.c ../libs/utils/utils.c ../libs/mat_fast_exp.c ../libs/matrix_mul/matrix_mul.c -o test_rahmenprogramm -g -Wall -Wextra -Wpedantic -std=c17 -lm -msse4.1
clear:
	rm test_rahmenprogramm
